"use client";

import React, { useState, useEffect, useCallback } from "react";
import dynamic from "next/dynamic";
import { useTranslations } from "next-intl";
import { useLotteryStore } from "@/utils/lotteryStore";
import { LotteryState } from "@/types/types";
import ControlPanel from "@/components/ball/ControlPanel";
import RightToolbar from "@/components/ball/RightToolbar";
import DataManager from "@/components/ball/DataManager";
import WinnerAnimation from "@/components/ball/WinnerAnimation";
import SettingsModal from "@/components/ball/SettingsModal";
import WinnerResultsModal from "@/components/ball/WinnerResultsModal";
import HelpModal from "@/components/ball/HelpModal";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import DynamicSEO from "@/components/SEO/DynamicSEO";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faKeyboard } from "@fortawesome/free-solid-svg-icons";

// Dynamic import 3D scene component to avoid SSR issues
const SphereScene = dynamic(() => import("@/components/3d/SphereScene"), {
  ssr: false,
  loading: () => {
    // Use a component function to access translations
    function LoadingComponent() {
      const t = useTranslations("Ball");
      return (
        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-yellow-400 via-orange-500 to-red-500 text-white">
          <div className="text-center">
            <div className="animate-spin w-12 h-12 border-4 border-white border-t-transparent rounded-full mx-auto mb-4"></div>
            <div className="text-lg">{t("loading3DScene")}</div>
            <div className="text-sm text-white/70 mt-2">
              {t("initializingThreeJS")}
            </div>
          </div>
        </div>
      );
    }
    return <LoadingComponent />;
  },
});

// Shortcut display component
function ShortcutDisplay() {
  const t = useTranslations("Ball");
  return (
    <div className="fixed bottom-6 left-6 z-50 bg-red-600/40 text-yellow-100 p-3 rounded-lg shadow-xl backdrop-blur-sm text-xs border border-yellow-300/30">
      <div className="flex items-center space-x-2 mb-1">
        <FontAwesomeIcon icon={faKeyboard} className="text-yellow-300" />
        <span className="font-semibold text-yellow-200">
          {t("shortcutsTitle")}
        </span>
      </div>
      <ul className="space-y-0.5">
        <li>
          <kbd className="px-1.5 py-0.5 bg-yellow-400/30 rounded text-xs text-yellow-100 font-mono">
            Space
          </kbd>
          : {t("spaceKeyDesc")}
        </li>
        <li>
          <kbd className="px-1.5 py-0.5 bg-yellow-400/30 rounded text-xs text-yellow-100 font-mono">
            Ctrl/Cmd+R
          </kbd>
          : {t("rKeyDesc")}
        </li>
        <li>
          <kbd className="px-1.5 py-0.5 bg-yellow-400/30 rounded text-xs text-yellow-100 font-mono">
            Esc
          </kbd>
          : {t("escKeyDesc")}
        </li>
      </ul>
    </div>
  );
}

export default function BallLotteryPage() {
  const t = useTranslations("Ball");
  const [isDataManagerOpen, setIsDataManagerOpen] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isClient, setIsClient] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isResultsOpen, setIsResultsOpen] = useState(false);
  const [isHelpOpen, setIsHelpOpen] = useState(false);

  const {
    participants,
    winners,
    loadFromStorage,
    resetLottery,
    state,
    settings,
    loadSettings,
    loadHistoryWinners,
  } = useLotteryStore();

  // Ensure client-side only execution and complete data restoration
  useEffect(() => {
    setIsClient(true);
    // Load all data in sequence to ensure complete restoration
    const initializeData = async () => {
      // 1. Load settings first
      loadSettings();
      // 2. Then load participants and winners data
      loadFromStorage();
      // 3. Finally load historical winners records
      loadHistoryWinners();
    };

    // Listen for auto-generated participants event
    const handleAutoGenerated = (event: CustomEvent) => {
      const { count } = event.detail;
      // Show notification message
      if (typeof window !== "undefined") {
        setTimeout(() => {
          alert(t("autoGeneratedParticipants", { count }));
        }, 500); // Delay 500ms to ensure page loading is complete
      }
    };

    window.addEventListener(
      "autoGeneratedParticipants",
      handleAutoGenerated as EventListener
    );

    initializeData();

    return () => {
      window.removeEventListener(
        "autoGeneratedParticipants",
        handleAutoGenerated as EventListener
      );
    };
  }, []); // Remove dependencies, execute only once when component mounts

  // Handle fullscreen toggle
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement
        .requestFullscreen()
        .then(() => {
          setIsFullscreen(true);
        })
        .catch((err) => {
          console.error("Error attempting to enable fullscreen:", err);
        });
    } else {
      document
        .exitFullscreen()
        .then(() => {
          setIsFullscreen(false);
        })
        .catch((err) => {
          console.error("Error attempting to exit fullscreen:", err);
        });
    }
  };

  // Listen for fullscreen state changes
  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };

    document.addEventListener("fullscreenchange", handleFullscreenChange);
    return () => {
      document.removeEventListener("fullscreenchange", handleFullscreenChange);
    };
  }, []);

  // Handle data import
  const handleImport = () => {
    setIsDataManagerOpen(true);
  };

  const handleReset = useCallback(() => {
    if (winners.length > 0 || participants.length > 0) {
      const confirmed = confirm(t("confirmResetMessage"));
      if (confirmed) {
        resetLottery();
      }
    }
  }, [winners, participants, resetLottery, t]);

  // Keyboard shortcut for Reset (Ctrl/Cmd + R)
  useEffect(() => {
    const handleGlobalKeyPress = (event: KeyboardEvent) => {
      if ((event.ctrlKey || event.metaKey) && event.code === "KeyR") {
        event.preventDefault();
        // handleReset();
      }
      // Esc for fullscreen is handled by RightToolbar now or can be global here too
      if (event.code === "Escape" && isFullscreen) {
        event.preventDefault();
        toggleFullscreen();
      }
    };
    window.addEventListener("keydown", handleGlobalKeyPress);
    return () => window.removeEventListener("keydown", handleGlobalKeyPress);
  }, [handleReset, isFullscreen]); // Added isFullscreen dependency

  // WebGL support detection
  const checkWebGLSupport = () => {
    if (typeof window === "undefined") return true;

    try {
      const canvas = document.createElement("canvas");
      const gl =
        canvas.getContext("webgl") || canvas.getContext("experimental-webgl");
      return !!gl;
    } catch {
      return false;
    }
  };

  const webGLSupported = checkWebGLSupport();

  if (!isClient) {
    return (
      <div className="w-full h-screen flex items-center justify-center bg-gradient-to-br from-yellow-400 via-orange-500 to-red-500 text-white">
        <div className="text-center">
          <div className="animate-spin w-12 h-12 border-4 border-white border-t-transparent rounded-full mx-auto mb-4"></div>
          <div className="text-lg">{t("initializingScene")}</div>
        </div>
      </div>
    );
  }

  if (!webGLSupported) {
    return (
      <div className="w-full h-screen flex items-center justify-center bg-gradient-to-br from-red-900 to-black text-white p-8">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-6">⚠️</div>
          <h1 className="text-2xl font-bold mb-4">{t("webglNotSupported")}</h1>
          <p className="text-gray-300 mb-6">{t("browserUpgrade")}</p>
          <button
            onClick={() => window.location.reload()}
            className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-lg transition-colors"
          >
            {t("reload")}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`
      relative w-full h-screen overflow-hidden bg-gradient-to-br from-yellow-400 via-orange-500 to-red-500 ball-scrollbar-theme
      ${isFullscreen ? "cursor-none" : ""}
    `}
    >
      {/* Dynamic SEO Component */}
      <DynamicSEO
        participantCount={participants.length}
        winnerCount={winners.length}
        isDrawing={state !== LotteryState.IDLE}
        prizeTypes={[settings.prizeType]}
      />
      {/* Page title and description - shown only in non-fullscreen mode */}
      {!isFullscreen && (
        <div className="absolute top-4 left-4 z-30 text-yellow-200">
          <h1 className="text-2xl font-bold mb-2 text-yellow-100 drop-shadow-md">
            {settings.pageTitle || t("title")}
          </h1>
          <p className="text-sm text-yellow-200 max-w-md drop-shadow-sm">
            {t("description")}
          </p>
        </div>
      )}

      {/* Top-right status info and language switcher - shown only in non-fullscreen mode */}
      {!isFullscreen && (
        <div className="absolute top-4 right-4 z-30 text-yellow-100 text-right space-y-3">
          {/* Language switcher */}
          <div className="flex justify-end">
            <LanguageSwitcher />
          </div>

          {/* Status information */}
          <div className="bg-red-600/30 backdrop-blur-sm rounded-lg p-3 text-sm border border-yellow-300/20">
            <div className="space-y-1">
              <div className="text-yellow-200 font-medium">
                {t("totalParticipants")}: {participants.length}
              </div>
              <div className="text-green-300 font-medium">
                {t("totalWinners")}: {winners.length}
              </div>
              <div className="text-orange-300 font-medium">
                {t("remainingPool")}: {participants.length - winners.length}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 3D sphere scene */}
      <div className="absolute inset-0">
        <SphereScene />
      </div>

      {/* Control panel */}
      <ControlPanel />

      <RightToolbar
        onImport={handleImport}
        onToggleFullscreen={toggleFullscreen}
        isFullscreen={isFullscreen}
        onReset={handleReset}
        onHelp={() => setIsHelpOpen(true)}
        onSettings={() => setIsSettingsOpen(true)}
        onShowResults={() => setIsResultsOpen(true)}
      />

      <ShortcutDisplay />

      {/* Data manager */}
      <DataManager
        isOpen={isDataManagerOpen}
        onClose={() => setIsDataManagerOpen(false)}
      />

      {/* Settings modal */}
      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
      />

      {/* Winner results modal */}
      <WinnerResultsModal
        isOpen={isResultsOpen}
        onClose={() => setIsResultsOpen(false)}
      />

      {/* Help modal */}
      <HelpModal isOpen={isHelpOpen} onClose={() => setIsHelpOpen(false)} />

      {/* Winner animation */}
      <WinnerAnimation />

      {/* Welcome/loading prompt */}
      {participants.length === 0 && state === LotteryState.IDLE && (
        <div className="absolute inset-0 flex items-center justify-center bg-orange-900/70 backdrop-blur-sm z-10">
          <div className="bg-gradient-to-br from-orange-500/20 to-yellow-500/20 backdrop-blur-md rounded-2xl p-8 text-white text-center border border-yellow-400/30 shadow-2xl">
            <div className="text-4xl mb-4">🎲</div>
            <h2 className="text-xl font-semibold mb-4 text-yellow-100 drop-shadow-lg">
              {settings.pageTitle || t("title")}
            </h2>
            <p className="text-yellow-200/90 mb-6">{t("welcomeMessage")}</p>
            <button
              onClick={handleImport}
              className="bg-gradient-to-r from-orange-500 to-yellow-500 hover:from-orange-600 hover:to-yellow-600 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-200 shadow-lg hover:shadow-xl transform hover:scale-105"
            >
              {t("manageParticipants")}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
